### ISSUE TITLE
Limit the source namespace for a Secret or ConfigMap

### ISSUE THREAD

**Issue by maunavarro** [emberstack/kubernetes-reflector#186]
Would it be possible to limit the source Secret or ConfigMap used by the reflector to a namespace? For example, only want the reflector to copy a source Secret to other namespaces **ONLY** if it comes from a specific namespace. 

This would be for security reasons as you wouldn't want any user with access to a namespace to apply the correct annotations and copy those secrets to other namespaces (spamming other namespaces).

I'm assuming this would have to be enabled in the controller via the values file. 

I thought the below would do the trick but it only limits the copying **to** those namespaces (and not **from** those namespaces) and it's applied to Secret directly (and not via Controller):
`reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "<list>"`

**Comment by ryaneorth** [comment]
Any update or thoughts on this @winromulus? Unfortunately, this missing security control is blocking us from using reflector.

**Comment by DirkDittmarMonday** [comment]
Hi, we're also interested in such a feature... could this ticket changed to "open" again?
We like to have the limitation to certain namespaces for security reasons. We want "reflector" not to see (or look at) *all* namespaces.

**Comment by gnunn1** [comment]
+1 on this, this feels like a serious security issue if tenants can create secrets or other resources in their namespaces and just annotate them to have reflector mirror them into system namespaces with no oversight or control. While reflector will skip a conflicting resources, this doesn't help you if the operator/controller/pod in the target namespace is picking up resources via a selector instead of a reference to a name. 

I would also like to see this re-opened and addressed.
