### ISSUE TITLE
Allow reflecting without annotating the source secret?

### ISSUE THREAD

**Issue by fzyzcjy** [emberstack/kubernetes-reflector#276]
Hi thanks for the lib! The case is that, I cannot control the source secret (which is auto-generated by elastic operator, see https://discuss.elastic.co/t/disable-apm-token-or-add-custom-annotations-to-it/301981). But I need to reflect it into another namespace. Thus, I would appreciate it if this operator can allow reflecting without annotating the source secret, and only annotating the target secret. Thanks!

**Comment by fzyzcjy** [comment]
not

**Comment by winromulus** [comment]
hi @fzyzcjy 
We cannot support this since this is a major security risk (reflector relies on annotations for permissions otherwise anyone would create a target secret, annotate it to reflect a source secret from a namespace where they do not have access and get a copy).
This will not be supported unfortunately.  I'm sorry if this breaks what you had planned but even with a feature flag this would be too much of a problem for security.

**Comment by fzyzcjy** [comment]
I see. Thank you!

**Comment by blackliner** [comment]
In our case, we do not have control over the secrets we want to reflect. Specifically, the rook operator creates secrets with access keys to a bucket, and we would have to use some sort of admission controll to add a annotation. Our hope was that we could tell reflector to allow copying from a whitelisted source namespace instead.
