### ISSUE TITLE
When tls secret is deleted reflector does not create it automatically.

### ISSUE THREAD

**Issue by Sayyadd** [emberstack/kubernetes-reflector#324]
I am creating certificate in certificates namespace and setting that create it's tls secret under test namespace.
Reflector creates secret under test namespace, but when I delete secret manually under that namespace, reflector does not create again.

**Comment by Sayyadd** [comment]
I am creating certificate in certificates namespace and setting that create it's tls secret under test namespace.
Reflector creates secret under test namespace, but when I delete secret manually under that namespace, reflector does not create again.

**Comment by PeterSR** [comment]
I am not sure if it's the same issue, but when reflector skips creating/updating a secret due to a conflict, i.e. the secret already exists in the namespace, perhaps because it was created manually previously, then after the manually created secret has been deleted, reflector does not seem to create its own mirrored version.

**Comment by winromulus** [comment]
@Sayyadd this is by design. Reflector will not recreate a secret unless the source has changed otherwise you can end up in a situation where you DO want to delete the copy until another change occurs but you can't stop  reflector from creating it again.
If I misunderstood the problem, please reopen the issue.

**Comment by ragrag** [comment]
@winromulus sorry for bringing this issue back, there are some cases where it will make sense to recreate secrets, (for example cases where namespace is re-created)
