### ISSUE TITLE
Exclude keys from reflected secret

### ISSUE THREAD

**Issue by StFS** [emberstack/kubernetes-reflector#367]
I assume the answer is no since I find nothing about this in the documentation but I was wondering whether it was possible to exclude certain keys when reflecting a secret.

My specific use case is when I use `cert-manager` to create a certificate which in turn generates a Secret containing the `ca.crt`, `tls.crt` and `tls.key` keys. I would like to reflect this secret to different namespaces but there is no need to reflect the `tls.key` there, I only need the `tls.crt` and `ca.crt`values.

I think this could be a nice feature to have so if (like I assume) the answer to my question is that this is not supported, then we can consider this issue a feature request ;)

**Comment by winromulus** [comment]
@StFS there is no such functionality currently built-in. Reflector would also have to be aware if the secret type validation would pass (some secret types require some keys to always be present).
Reflector currently just copies the data without any manipulation.

**Comment by L1ghtman2k** [comment]
Can this be turned into a feature request? There is an equivalent ticket open for kubernetes-replicator https://github.com/mittwald/kubernetes-replicator/issues/248. In my specific case, I have created my own CA with cert-manager, and I would like to propagate ca.crt across all namespaces, so that clients can verify the remote cert against the ca.crt
